# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptNumber', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10)),
                ('event', models.CharField(max_length=20)),
            ],
        ),
    ]
