# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20180528_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptNumber', models.PositiveSmallIntegerField(error_messages={'unique': 'This email has already been registered.'}, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10)),
                ('event', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
