# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20180604_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptNumber', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=2)),
                ('college', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptNumber', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=2)),
                ('event', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='receiptNumber',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
